### PR TITLE
Add `totalResults` property

### PR DESCRIPTION
**Pull request by vpchung**
With this PR:

- `totalResults: <integer>` property is added to the ResponsePageMetadata schema (#37)

~~Note: to be merged after #53~~

### CODE REVIEW

**Comment by vpchung** [comment]
@tschaffter ready for review!

**Comment by vpchung** [comment]
Whoops, that last commit was meant for the `refactor` branch 😅

**Comment by tschaffter** [comment]
> Whoops, that last commit was meant for the refactor branch 😅

Then I'm going to ask you a question from the IBC phone interview for BE: "How would you undo a commit that you did to a wrong branch?" Your answer? ;-) (You can tell me in Slack)

**Review by tschaffter — APPROVED** [review]
This looks good!

**Pull request merged**
