### PR TITLE
Refactor schemas

### PR DESCRIPTION
**Pull request by vpchung**
With this PR:

- update status codes and returned response objects for POST and DELETE operations (#42, #43, #51) 
- suggest which properties to be required among the established entities (#45)
- reformat examples to be at the object-level rather than property level (#46)
- add new *CreateRequest schemas for POST operations (#44)

With respect to the examples, I looked into whether the schemas should use examples at the property- or object-level, as well as in an external file. I didn't like the property-level examples as it made maintaining a little more tedious (especially if the schema has numerous properties that would need updating); using the object-level approach made it so that all of the example values was in one general area of the schema, which is preferable to me. As for object-level vs `externalValue`, because the example values can be specified in YAML format, I ultimately did not go for the latter option to keep things more simplistic. I can see an argument for external examples however, so happy to discuss more.

As for the \*CreateRequest schemas, I had only created them for the Challenge, Grant, and Person entities; I did not see a purpose for Organization* or Tag* (since the user will be creating the ID). I also did not rename the original entities to *CreateResponse as I prefer the former. In my opinion, `Challenge` is more descriptive than `ChallengeCreateReponse`.

~~Note: to be merged after #52~~

### CODE REVIEW

**Comment by vpchung** [comment]
@tschaffter ready for review! I have made the following changes to the refactor:

- move parameter "schemas", e.g. ChallengeId.yaml, TagId.yaml, to a new `parameters/` folder, much like what is done in `nlpsandbox`
- create new response schemas for the POST operations; now, a JSON object containing the entity ID is returned rather than a string
- update the `$ref` paths in the relative `schemas/` and `paths/` YAML files

For update # 2 (new response schemas), I debated between two directory structures:

* having them in the `schemas/` folder where the names are \*CreateResponse.yaml
* having them in the `responses/` folder where the names are \*Response.yaml

I went with the second approach, because I figured all the response schemas can be in one place. I don't care too much about the naming conventions -- I just went with the one that saved me some typing :-) But happy to go with \*CreateResponse.yaml to keep things consistent with the \*CreateRequest schemas!

**Comment by vpchung** [comment]
@tschaffter Okay, NOW officially ready for review :laughing:

As mentioned, #52 is closed as changes there are also found here (so no need to review the other). Main description of the PR has been updated, but for convenience, updates implemented are:

- update status codes and response objects for POST and DELETE operations, e.g. JSON object containing just the entity ID and empty JSON object, respectively
- suggest which properties to be required among the established entities
- reformat examples to be at the object-level rather than property level
- add new *CreateRequest and *CreateResponse schemas for POST operations (to tackle the readOnly issue experienced with the openapi generator)

Also for convenience, updates to the docs page are as expected:

post_operation

delete_operation

**Comment by tschaffter** [comment]
> As for the *CreateRequest schemas, I had only created them for the Challenge, Grant, and Person entities; I did not see a purpose for Organization* or Tag* (since the user will be creating the ID).

I think that consistency is more important here than not returning a piece of information because the client has passed it as input. This consistency calls for returning 201, which means that we return a reference to the created entity, whether this reference has been passed by the client itself or has been generated by the service.

> I also did not rename the original entities to *CreateResponse as I prefer the former. In my opinion, Challenge is more descriptive than ChallengeCreateReponse.

The idea is not to rename the original entities. For example, `Challenge` and `ChallengeCreateResponse` are meant to be different:

- `Challenge`: the entire challenge object as returned by getChallenge and listChallenges
- `ChallengeCreateResponse`: used on to return the POST response, which is an object with a single property that is the reference to the created entity.

**Comment by tschaffter** [comment]
> I went with the second approach, because I figured all the response schemas can be in one place.

For future references, Verena and I have decided to keep the folder `components/responses/` for true OpenAPI response objects. Schema objects `<resource>CreateRequest` and `<resource>CreateResponse` are placed in `components/schemas`. For now we don't use sub-folders because `components/schemas/responses/` may be ill defined. Sub-folders have definitively their place in the future, but a naming convention should be adopted first.

**Comment by vpchung** [comment]
>The idea is not to rename the original entities. For example, `Challenge` and `ChallengeCreateResponse` are meant to be different
Sorry, I should've updated my comments.  After working with the schemas a bit, I understood the purpose of all the various schemas per entity, e.g. `Challenge` vs `ChallengeCreateResponse` vs `ChallengeCreateRequest`

**Comment by vpchung** [comment]
>I think that consistency is more important here than not returning a piece of information because the client has passed it as input. This consistency calls for returning 201, which means that we return a reference to the created entity...

Just wanted to clarify --
Organization and Tag do have a corresponding \*CreateResponse object (what is being returned with `201`)... I didn't, however, create a corresponding \*CreateRequest object, as I found it redundant with the original schema.

**Comment by tschaffter** [comment]
> Organization and Tag do have a corresponding *CreateResponse object (what is being returned with 201). I didn't, however, create a corresponding *CreateRequest object for them

The schemas `Challenge` and `ChallengeCreateRequest` would indeed be similar but still different: `Challenge` has an ID while `ChallengeCreateRequest` don't. The OpenAPI way to solve this is to use `readOnly` for the ID property, but OpenAPI currently does not support `readOnly` with `$ref` properties. This will change in the next OpenAPI release. Meanwhile, the solution proposed is to have `Challenge` and `ChallengeCreateRequest`. The duplication of code is not ideal but this brings two benefits:

- The documentation is more clear as the request body schema does not include the ID property included in the schema `Challenge`
- Defining systematically `<resource>CreateRequest` and `<resource>CreateResspone` for POST requests increases the consistency of our APIs

We will revise this design once OpenAPI supports `readOnly` with `$ref`.

**Comment by vpchung** [comment]
>We will revise this design once OpenAPI supports `readOnly` with `$ref`. Meanwhile, I recommend preferring documentation clarity to limited code duplication.

By support, do you mean that the generator will also generate flask files that will take into account the read-only (and write-only) property? Because if not, then we will probably continue having the same issue as we do now (so not sure if it'd be worth exploring).

Case in point:
Last week, I explored to see whether we could add `readOnly` to the parameter schemas and if it'll work all the way through to the server-side. (I know we wouldn't move forward with this plan, since we don't want the actual parameter to be read-only, just the reference to it in the schema). From the docs side, everything is working as expected, e.g. \*ID does not show up in the request body for POST:

Screen Shot 2021-01-19 at 10 33 54 AM

But when generating the server files, we hit the same problem as before, where \*ID is shown as expected in the request body example.  At least it does return a "read only" error if the user just submits the example as-is :grimacing: :

Screen Shot 2021-01-19 at 10 48 49 AM

---

 > The schemas `Challenge` and `ChallengeCreateRequest` would indeed be similar but still different: `Challenge` has an ID while `ChallengeCreateRequest` don't.

Yes, I understand this. But with Organization and Tag, users are creating the IDs for these entities, not the database.  If consistency is the key (as in, OrganizationCreateRequest and TagCreateRequest should be created so that their POST request bodies are the same as Challenge, Grant, and Person), couldn't we also argue that the paths should follow the same structure, e.g.

* current Challenge request URL: `/api/v1/challenges`
* current Tag request URL: `/api/v1/tags?tagId=awesome-tag`

I guess we'll just have to decide which of the things we want to keep consistent? The request bodies or the paths.

**Comment by vpchung** [comment]
^^^ That all being said, I think I would prefer having consistent request bodies after all :sweat_smile:

**Comment by tschaffter** [comment]
> By support, do you mean that the generator will also generate flask files that will take into account the read-only (and write-only) property? Because if not, then we will probably continue having the same issue as we do now (so not sure if it'd be worth exploring).

You're right.

> From the docs side, everything is working as expected, e.g. *ID does not show up in the request body for POST:

Yes, the redocli HTML documentation is usually right on spot and show what we expect.

> But when generating the server files, we hit the same problem as before, where *ID is shown as expected in the request body example. At least it does return a "read only" error if the user just submits the example as-is 😬 :

One of the current main aim is for the user to be able to POST the example request body without getting on error from the backend (user friendliness +1). As a reminder, there are two components to this issue:

1. The documentation UI ignores `readOnly` when generating the example request body. This makes the documentation confusing.
2. The `connexion` package used to run the server throws a 400 error when specifying a property that is marked as `readOnly`. This behavior is being discussed in t[his `connexion` ticket](https://github.com/zalando/connexion/issues/942). According to the author of the ticket, this is not compliant with the OpenAPI spec that says ([ref](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-20)):

> Relevant only for Schema "properties" definitions. Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only. A property MUST NOT be marked as both readOnly and writeOnly being true. Default value is false.

Note the "SHOULD NOT" (=> should be warning/ignore) and not "MUST NOT" (ground for error).

The issue we could face could be solved by either 1) fixing the generation of the example request body or 2) having `connexion` not throwing an error when `readOnly` properties are specified.

@vpchung I'm wondering if we have enough control aver the examples to fix 1). For example, most of my tests have been made when I specified the example at the level of the schema property. Do you know if specifying the example at the schema level can solve 1), i.e. by not including in the example value for `readOnly` property? Actually, this would bring another issue because the example would not be correct for response payload that do need to show an example for readOnly value. An alternative could be to specify different examples in different files, and important the example at the path level. This may work but may be more trouble than it's worth.

That was basically my reasoning to go to the current design with different schemas for POST requests and responses.

**Comment by vpchung** [comment]
>That was basically my reasoning to go to the current design with different schemas for POST requests and responses.

Oh, I'm not at all saying that I'm against this approach of having multiple schemas per entity, e.g. `Challenge`, `ChallengeCreateRequest`, and `ChallengeCreateResponse`. For our current situation, they completely make sense and definitely work as intended. When testing on the server side, it all looks good:

Screen Shot 2021-01-19 at 1 36 04 PM

My original comment here:
*As for the \*CreateRequest schemas, I had only created them for the Challenge, Grant, and Person entities; I did not see a purpose for OrganizationCreateRequest or TagCreateRequest*

...was just to elucidate why I did not create the \*CreateRequest schemas for those two entities (since I thought it'd be redundant), not that I was against making them.

**Comment by vpchung** [comment]
@tschaffter two final schemas added -- now the PR is officially ready for the review... officially

meme

:-)

**Review by tschaffter — APPROVED** [review]
You aced this PR! Nicely done! 🚀

**Pull request merged**
